package com.ikould.decorate.mapper;

import org.springframework.stereotype.Repository;

import com.ikould.decorate.entity.Admin;

@Repository
public interface AdminMapper {

	Admin selectByName(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKey(Admin record);
}